# Generated by Django 4.2.28 on 2026-03-03 17:46

# Django
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("killstats", "0001_initial"),
        ("killstats", "0002_rename_killstatsaudit_corporationsaudit_and_more"),
        ("killstats", "0003_attacker_remove_killmail_attackers_and_more"),
        ("killstats", "0004_migrate_attacker"),
        ("killstats", "0005_alter_general_options"),
        ("killstats", "0006_alter_attacker_weapon_type_id_and_more"),
        ("killstats", "0007_eveentity"),
        ("killstats", "0008_alter_attacker_alliance_alter_attacker_character_and_more"),
    ]

    initial = True

    dependencies = [
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access this app, Killstats."),
                    ("admin_access", "Has access to all killstats."),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EveEntity",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("alliance", "Alliance"),
                            ("corporation", "Corporation"),
                            ("character", "Character"),
                        ],
                        max_length=32,
                        verbose_name="Category",
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "alliance",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alli",
                        to="killstats.eveentity",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corp",
                        to="killstats.eveentity",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Killmail",
            fields=[
                (
                    "killmail_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "killmail_date",
                    models.DateTimeField(blank=True, max_length=0, null=True),
                ),
                ("victim_corporation_id", models.PositiveIntegerField()),
                (
                    "victim_alliance_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("hash", models.CharField(max_length=255, unique=True)),
                (
                    "victim_total_value",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "victim_fitted_value",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "victim_destroyed_value",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "victim_dropped_value",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "victim_region_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "victim_solar_system_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("victim_position_x", models.FloatField(blank=True, null=True)),
                ("victim_position_y", models.FloatField(blank=True, null=True)),
                ("victim_position_z", models.FloatField(blank=True, null=True)),
                (
                    "victim",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="killstats.eveentity",
                    ),
                ),
                (
                    "victim_ship",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CorporationsAudit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "corporation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Attacker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage_done", models.IntegerField(blank=True, null=True)),
                ("final_blow", models.BooleanField(blank=True, null=True)),
                ("weapon_type_id", models.PositiveIntegerField(blank=True, null=True)),
                ("security_status", models.FloatField(blank=True, null=True)),
                (
                    "alliance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacker_alliance",
                        to="killstats.eveentity",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacker_character",
                        to="killstats.eveentity",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacker_corp",
                        to="killstats.eveentity",
                    ),
                ),
                (
                    "killmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacker_killmail",
                        to="killstats.killmail",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacker_ship",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AlliancesAudit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "alliance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.eveallianceinfo",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
