# Generated by Django 5.2.13 on 2026-09-20 14:04

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("killstats", "0001_init_v2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app, Killstats."),
                    ("admin_access", "Has access to all killstats."),
                ),
                "verbose_name": "AA-Killstats",
                "verbose_name_plural": "AA-Killstats",
            },
        ),
    ]
