# Generated by Django 5.2.13 on 2026-09-25 08:43

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("killstats", "0002_alter_general_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="alliancesaudit",
            name="last_missing_check",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="last missing check"
            ),
        ),
        migrations.AddField(
            model_name="corporationsaudit",
            name="last_missing_check",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="last missing check"
            ),
        ),
    ]
