# Generated by Django 4.2.11 on 2024-09-24 19:01

import django.db.models.deletion
from django.db import migrations, models, transaction
from eveuniverse.models import EveEntity, EveType

from killstats.models.killboard import Attacker, Killmail


def migrate_table(apps, schema_editor):
    print("Migrate Killstats Changes this can take a while...")
    runs = 0
    with transaction.atomic():
        killmail_list = Killmail.objects.all()
        if not killmail_list:
            return

        for killmail in killmail_list:
            print(f"Processing killmail {killmail.killmail_id}")
            EveEntity.objects.get_or_create_esi(id=killmail.victim_id)
            runs = runs + 1
            items = []
            for attacker in killmail.attackers:
                if attacker["character_id"] is not None:
                    character, _ = EveEntity.objects.get_or_create_esi(
                        id=attacker["character_id"]
                    )
                if attacker["corporation_id"] is not None:
                    corporation, _ = EveEntity.objects.get_or_create_esi(
                        id=attacker["corporation_id"]
                    )
                if attacker["alliance_id"] is not None:
                    alliance, _ = EveEntity.objects.get_or_create_esi(
                        id=attacker["alliance_id"]
                    )
                if attacker["ship_type_id"] is not None:
                    ship, _ = EveType.objects.get_or_create_esi(
                        id=attacker["ship_type_id"]
                    )

                items.append(
                    Attacker(
                        killmail=killmail,
                        character=character,
                        corporation=corporation,
                        alliance=alliance,
                        ship=ship,
                        damage_done=attacker.get("damage_done", None),
                        final_blow=attacker.get("final_blow", None),
                        weapon_type_id=attacker.get("weapon_type_id", None),
                        security_status=attacker.get("security_status", None),
                    )
                )

            Attacker.objects.bulk_create(items)
        print(f"Processed {runs} killmails")


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0010_alter_eveindustryactivityduration_eve_type_and_more"),
        ("killstats", "0002_rename_killstatsaudit_corporationsaudit_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_table),
        migrations.AlterField(
            model_name="killmail",
            name="victim",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eveuniverse.eveentity",
            ),
        ),
        migrations.CreateModel(
            name="Attacker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage_done", models.IntegerField(blank=True, null=True)),
                ("final_blow", models.BooleanField(blank=True, null=True)),
                (
                    "weapon_type_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("security_status", models.FloatField(blank=True, null=True)),
                (
                    "alliance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacker_alliance",
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacker",
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacker_corp",
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "killmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="killstats.killmail",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacker_ship",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
