# Generated by Django 4.2.11 on 2024-09-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("killstats", "0003_alter_killmail_victim_attacker"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EveEntity",
        ),
        migrations.RemoveField(
            model_name="killmail",
            name="attackers",
        ),
    ]
