# Generated by Django 5.2.13 on 2026-10-01 21:25

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0036_remove_star_name"),
        ("killstats", "0003_alliancesaudit_last_missing_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attacker",
            name="corporation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attacker_corporation",
                to="killstats.eveentity",
            ),
        ),
        migrations.AlterField(
            model_name="eveentity",
            name="alliance",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="killstats.eveentity",
            ),
        ),
        migrations.AlterField(
            model_name="eveentity",
            name="corporation",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="killstats.eveentity",
            ),
        ),
        migrations.AlterField(
            model_name="killmail",
            name="victim",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="victim_killmail",
                to="killstats.eveentity",
            ),
        ),
        migrations.AddIndex(
            model_name="attacker",
            index=models.Index(
                fields=["corporation_id", "killmail_id"], name="attacker_corp_km_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attacker",
            index=models.Index(
                fields=["alliance_id", "killmail_id"], name="attacker_ally_km_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attacker",
            index=models.Index(
                fields=["character_id", "killmail_id"], name="attacker_char_km_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attacker",
            index=models.Index(
                fields=["corporation_id", "final_blow"], name="attacker_corp_fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attacker",
            index=models.Index(
                fields=["alliance_id", "final_blow"], name="attacker_ally_fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attacker",
            index=models.Index(
                fields=["killmail_id", "final_blow"], name="att_km_final_blow_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eveentity",
            index=models.Index(
                fields=["category", "name"], name="eveentity_cat_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(fields=["killmail_date"], name="km_date_idx"),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(
                fields=["victim_corporation_id", "-killmail_date"],
                name="km_corp_loss_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(
                fields=["victim_alliance_id", "-killmail_date"], name="km_ally_loss_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(
                fields=["victim_corporation_id", "-victim_total_value"],
                name="km_corp_val_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(
                fields=["victim_alliance_id", "-victim_total_value"],
                name="km_ally_val_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(fields=["-victim_total_value"], name="km_val_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(fields=["victim_solar_system_id"], name="km_system_idx"),
        ),
    ]
