# Generated by Django 5.2.17 on 2026-09-29 12:30

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "killstats",
            "0004_alter_attacker_corporation_alter_eveentity_alliance_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attacker",
            index=models.Index(
                fields=["killmail_id", "final_blow"], name="att_km_final_blow_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eveentity",
            index=models.Index(
                fields=["category", "name"], name="eveentity_cat_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(fields=["-killmail_date"], name="km_date_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(
                fields=["victim_corporation_id", "-killmail_date"],
                name="km_corp_loss_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(
                fields=["victim_alliance_id", "-killmail_date"], name="km_ally_loss_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(
                fields=["victim_corporation_id", "-victim_total_value"],
                name="km_corp_val_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(
                fields=["victim_alliance_id", "-victim_total_value"],
                name="km_ally_val_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(fields=["-victim_total_value"], name="km_val_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="killmail",
            index=models.Index(fields=["victim_solar_system_id"], name="km_system_idx"),
        ),
    ]
