# Generated by Django 4.2.28 on 2026-03-03 17:01

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0014_dogmaeffect_description_de_and_more"),
        ("killstats", "0007_eveentity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attacker",
            name="alliance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attacker_alliance",
                to="killstats.eveentity",
            ),
        ),
        migrations.AlterField(
            model_name="attacker",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attacker_character",
                to="killstats.eveentity",
            ),
        ),
        migrations.AlterField(
            model_name="attacker",
            name="corporation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attacker_corp",
                to="killstats.eveentity",
            ),
        ),
        migrations.AlterField(
            model_name="attacker",
            name="ship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attacker_ship",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="killmail",
            name="victim",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="killstats.eveentity",
            ),
        ),
        migrations.AlterField(
            model_name="killmail",
            name="victim_ship",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eve_sde.itemtype",
            ),
        ),
    ]
