/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/killstats/api/stats/v2/attackers/{entity_type}/{entity_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top-10 attackers for an entity */
        get: operations["killstats_api_killboard_get_top_attackers_api"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/killstats/api/stats/v2/victims/{entity_type}/{entity_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top-10 victims for an entity */
        get: operations["killstats_api_killboard_get_top_victims_api"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/killstats/api/killmails/{entity_type}/{entity_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve killmails for an entity */
        get: operations["killstats_api_killboard_get_killmails_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/killstats/api/killboard/corporation/admin/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Corporation Admin */
        get: operations["killstats_api_admin_get_corporation_admin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/killstats/api/killboard/alliance/admin/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alliance Admin */
        get: operations["killstats_api_admin_get_alliance_admin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/killstats/api/hall/v2/{entity_type}/{entity_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve the hall of fame for an entity */
        get: operations["killstats_api_stats_get_hall_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/killstats/api/stats/v2/summary/{entity_type}/{entity_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fast summary: total kills, ISK & active PvPers */
        get: operations["killstats_api_stats_get_combat_summary_api"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/killstats/api/menu/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Killstats navigation menu */
        get: operations["killstats_api_general_get_menu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/killstats/api/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user data */
        get: operations["killstats_api_general_get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** TopPilotsFilter */
        TopPilotsFilter: {
            /**
             * Year
             * @description Filter by year (e.g. 2026)
             */
            year?: number | null;
            /**
             * Month
             * @description Filter by month (1-12)
             */
            month?: number | null;
            /**
             * Limit
             * @description Number of top pilots to return
             * @default 10
             */
            limit: number;
        };
        /** TopPilotSchema */
        TopPilotSchema: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Main Name */
            main_name?: string | null;
            /** Count */
            count: number;
            /** Total Value */
            total_value: number;
        };
        /**
         * TopPilotsResponse
         * @description Top-N pilot list (attackers OR victims). Returned by dedicated endpoints.
         */
        TopPilotsResponse: {
            /** Pilots */
            pilots: components["schemas"]["TopPilotSchema"][];
        };
        /** KillmailFilter */
        KillmailFilter: {
            /**
             * Year
             * @description Filter by year (e.g. 2026)
             */
            year?: number | null;
            /**
             * Month
             * @description Filter by month (1-12)
             */
            month?: number | null;
            /**
             * Mode
             * @description Mode filter
             * @default all
             * @enum {string}
             */
            mode: "all" | "kills" | "losses";
            /**
             * Page
             * @description Page number
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @description Items per page
             * @default 50
             */
            page_size: number;
        };
        /** KillmailItemSchema */
        KillmailItemSchema: {
            /** Killmail Id */
            killmail_id: number;
            /** Killmail Date */
            killmail_date: string;
            /** Victim Id */
            victim_id: number;
            /** Victim Name */
            victim_name: string;
            /** Victim Ship Id */
            victim_ship_id: number;
            /** Victim Ship Name */
            victim_ship_name: string;
            /** Total Value */
            total_value: number;
            /**
             * Solar System Id
             * @default 0
             */
            solar_system_id: number;
            /**
             * Solar System Name
             * @default Unknown
             */
            solar_system_name: string;
            /**
             * Security Status
             * @default 0
             */
            security_status: number;
            /** Pilot Count */
            pilot_count: number;
            /**
             * Final Blow Id
             * @default 0
             */
            final_blow_id: number;
            /**
             * Final Blow Name
             * @default Unknown
             */
            final_blow_name: string;
            /**
             * Is Loss
             * @default false
             */
            is_loss: boolean;
            /** Zkb Link */
            zkb_link: string;
        };
        /** KillmailListResponse */
        KillmailListResponse: {
            /** Killmails */
            killmails: components["schemas"]["KillmailItemSchema"][];
            /** Total */
            total: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 50
             */
            page_size: number;
        };
        /** CorporationAdmin */
        CorporationAdmin: {
            /** Corporation */
            corporation?: {
                [key: string]: unknown;
            } | null;
        };
        /** AllianceAdmin */
        AllianceAdmin: {
            /** Alliance */
            alliance?: {
                [key: string]: unknown;
            } | null;
        };
        /** HallFilter */
        HallFilter: {
            /**
             * Year
             * @description Filter by year (e.g. 2026)
             */
            year?: number | null;
            /**
             * Month
             * @description Filter by month (1-12)
             */
            month?: number | null;
            /**
             * Limit
             * @description Number of hall entries to return
             * @default 5
             */
            limit: number;
        };
        /** HallEntrySchema */
        HallEntrySchema: {
            /** Killmail Id */
            killmail_id: number;
            /** Char Id */
            char_id: number;
            /** Char Name */
            char_name: string;
            /**
             * Ship Id
             * @default 0
             */
            ship_id: number;
            /**
             * Ship Name
             * @default Unknown
             */
            ship_name: string;
            /**
             * Victim Ship Id
             * @default 0
             */
            victim_ship_id: number;
            /**
             * Victim Ship Name
             * @default Unknown
             */
            victim_ship_name: string;
            /** Total Value */
            total_value: number;
            /**
             * Damage Done
             * @default 0
             */
            damage_done: number;
            /** Zkb Link */
            zkb_link: string;
        };
        /** HallResponseSchema */
        HallResponseSchema: {
            /** Hall Of Fame */
            hall_of_fame: components["schemas"]["HallEntrySchema"][];
            /** Hall Of Shame */
            hall_of_shame: components["schemas"]["HallEntrySchema"][];
        };
        /** DateRangeFilter */
        DateRangeFilter: {
            /**
             * Year
             * @description Filter by year (e.g. 2026)
             */
            year?: number | null;
            /**
             * Month
             * @description Filter by month (1-12)
             */
            month?: number | null;
        };
        /**
         * CombatSummaryResponse
         * @description Lightweight summary: counters + ISK totals only. Fast to compute.
         */
        CombatSummaryResponse: {
            /** Total Kills */
            total_kills: number;
            /** Active Pvpers */
            active_pvpers: number;
            /** Destroyed Isk */
            destroyed_isk: number;
            /** Lost Isk */
            lost_isk: number;
        };
        /**
         * MenuLink
         * @description Represents a link in the menu.
         */
        MenuLink: {
            /** Name */
            name: string;
            /** Link */
            link?: string | null;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
        };
        /**
         * MenuModalSchema
         * @description Schema for menu modals.
         */
        MenuModalSchema: {
            modal?: components["schemas"]["ModalSchema"] | null;
        };
        /**
         * MenuSchema
         * @description Schema for the overall menu, including links and modals.
         */
        MenuSchema: {
            /**
             * Left Links
             * @default []
             */
            left_links: components["schemas"]["MenuLink"][];
            /**
             * Right Links
             * @default []
             */
            right_links: components["schemas"]["MenuLink"][];
            modals?: components["schemas"]["MenuModalSchema"] | null;
        };
        /**
         * ModalSchema
         * @description Schema for modal dialog data.
         */
        ModalSchema: {
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Icon */
            icon: string;
            /** Modal Id */
            modal_id: string;
            /** Url */
            url: string;
            /** Color */
            color?: string | null;
            /** Buttontext */
            buttonText?: string | null;
        };
        /**
         * UserData
         * @description Schema for user data, including character ID and character name.
         */
        UserData: {
            /** User Id */
            user_id: number;
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Corporation Id */
            corporation_id: number;
            /** Corporation Name */
            corporation_name: string;
            /** Alliance Id */
            alliance_id?: number | null;
            /** Alliance Name */
            alliance_name?: string | null;
            /** Portrait */
            portrait?: string | null;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    killstats_api_killboard_get_top_attackers_api: {
        parameters: {
            query?: {
                /** @description Filter by year (e.g. 2026) */
                year?: number | null;
                /** @description Filter by month (1-12) */
                month?: number | null;
                /** @description Number of top pilots to return */
                limit?: number;
            };
            header?: never;
            path: {
                entity_type: "alliance" | "corporation" | "character";
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopPilotsResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    killstats_api_killboard_get_top_victims_api: {
        parameters: {
            query?: {
                /** @description Filter by year (e.g. 2026) */
                year?: number | null;
                /** @description Filter by month (1-12) */
                month?: number | null;
                /** @description Number of top pilots to return */
                limit?: number;
            };
            header?: never;
            path: {
                entity_type: "alliance" | "corporation" | "character";
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopPilotsResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    killstats_api_killboard_get_killmails_endpoint: {
        parameters: {
            query?: {
                /** @description Filter by year (e.g. 2026) */
                year?: number | null;
                /** @description Filter by month (1-12) */
                month?: number | null;
                /** @description Mode filter */
                mode?: "all" | "kills" | "losses";
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path: {
                entity_type: "alliance" | "corporation" | "character";
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillmailListResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    killstats_api_admin_get_corporation_admin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationAdmin"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    killstats_api_admin_get_alliance_admin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllianceAdmin"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    killstats_api_stats_get_hall_endpoint: {
        parameters: {
            query?: {
                /** @description Filter by year (e.g. 2026) */
                year?: number | null;
                /** @description Filter by month (1-12) */
                month?: number | null;
                /** @description Number of hall entries to return */
                limit?: number;
            };
            header?: never;
            path: {
                entity_type: "alliance" | "corporation" | "character";
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallResponseSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    killstats_api_stats_get_combat_summary_api: {
        parameters: {
            query?: {
                /** @description Filter by year (e.g. 2026) */
                year?: number | null;
                /** @description Filter by month (1-12) */
                month?: number | null;
            };
            header?: never;
            path: {
                entity_type: "alliance" | "corporation" | "character";
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CombatSummaryResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    killstats_api_general_get_menu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuSchema"];
                };
            };
        };
    };
    killstats_api_general_get_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserData"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
